spring:
  jpa:
    database: h2
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
  datasource:
    schema: classpath:h2/schema.sql
    data: classpath:h2/data.sql
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  # 当需要启动H2控制台时需要开启下面当配置
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:9090

management:
  endpoints:
    web:
      exposure:
        include: '*'

