spring:
  jpa:
    database: h2
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
  datasource:
    schema: classpath:h2/schema.sql
    data: classpath:h2/data.sql
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  # 当需要启动H2控制台时需要开启下面当配置
  h2:
    console:
      enabled: true
      path: /h2-console
  # spring-boot-admin配置
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:9090

# spring-boot-admin配置
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 日志配置
logging:
  file:
    name: logs/web.log  # logs前面没有'/'表示相对路径(当前项目做为根路径)，反之则表示绝对路径
  level:
    com:
      x:
        web: debug
    org:
      springframework: info
      hibernate: debug

